name: KeepNote
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.1
  path_provider: ^2.0.11
  fluttertoast: ^8.1.1
  cupertino_icons: ^1.0.2
  rflutter_alert: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
